version: "2"
run:
  timeout: 3m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - gosec
    - errcheck
    - unconvert
    - gocyclo
    - revive
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports
